name: vlc-pi
base: core20
adopt-info: vlc
summary: VLC snap built with accelerated playback support (MMAL) for Raspberry Pi
description: |
  This snap of VLC is specifically created for the Raspberry Pi, it includes the MMAL
  (Multi-Media Abstraction Layer) VLC patches from https://github.com/RPi-Distro/vlc,
  an MMAL patched version of FFmpeg as found at https://github.com/RPi-Distro/ffmpeg and
  the accelerated videocore binaries from https://github.com/raspberrypi/firmware.

  Please make sure your user is in the "video" group to gain access to the /dev/vchiq device.
  If you have problems with fullscreen playback on a Pi4 or Pi400, make sure your screen is
  connected to the correct HDMI output (this VLC can only play fullscreen on one of them).

  Please make also sure to have the "hardware-observe" interface connected via
  
      sudo snap connect vlc-pi:hardware-observe

grade: stable
confinement: devmode
compression: lzo

architectures:
  - build-on: armhf
    run-on: [ armhf, arm64 ]

apps:
  vlc-pi:
    desktop: usr/share/applications/vlc.desktop
    command: bin/checks $SNAP/bin/locales-launch $SNAP/bin/desktop-launch $SNAP/usr/bin/vlc
    environment:
      LD_LIBRARY_PATH: "$SNAP/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri:$SNAP/usr/lib/vlc:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/oss4-libsalsa:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/samba:$SNAP/usr/lib"
      KDE_FORK_SLAVES: "1"
      KF5_LIBEXEC_DIR: "$SNAP/usr/lib/$ARCH/libexec/kf5"
      QML2_IMPORT_PATH: "$QML2_IMPORT_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/qml/"
    plugs:
      - audio-record
      - audio-playback
      - avahi-control
      - camera
      - desktop
      - dvb
      - hardware-observe
      - home
      - jack1
      - mount-observe
      - network
      - network-bind
      - opengl
      - optical-drive
      - removable-media
      - screen-inhibit-control
      - unity7
      - x11
    slots:
      - mpris
  cvlc:
    command: bin/checks $SNAP/bin/locales-launch $SNAP/bin/desktop-launch $SNAP/usr/bin/cvlc
    environment:
      LD_LIBRARY_PATH: "$SNAP/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri:$SNAP/usr/lib/vlc:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/oss4-libsalsa:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/samba:$SNAP/usr/lib"
      KDE_FORK_SLAVES: "1"
      KF5_LIBEXEC_DIR: "$SNAP/usr/lib/$ARCH/libexec/kf5"
      QML2_IMPORT_PATH: "$QML2_IMPORT_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/qml/"
    plugs:
      - audio-record
      - audio-playback
      - avahi-control
      - camera
      - desktop
      - dvb
      - hardware-observe
      - home
      - jack1
      - mount-observe
      - network
      - network-bind
      - opengl
      - optical-drive
      - removable-media
      - screen-inhibit-control
      - unity7
      - x11
    slots:
      - mpris

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa/alsa.conf:
    bind-file: $SNAP/usr/share/alsa/alsa.conf

parts:
  pi-libs:
    source: https://github.com/raspberrypi/firmware.git
    source-depth: 1
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr
      cp -av hardfp/opt/vc/bin $SNAPCRAFT_PART_INSTALL/usr/
      cp -av hardfp/opt/vc/lib $SNAPCRAFT_PART_INSTALL/usr/
      cp -av hardfp/opt/vc/include $SNAPCRAFT_PART_INSTALL/usr/
      # we want to link against mesa, drop GLES and EGL includes
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/include/*GL*
    prime:
      - -usr/include
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt/
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - locales-all
      - libgtk2.0-0
      - libatk1.0-0
      - libxrandr2
      - libxinerama1
      - libxi6
      - libxcursor1
      - libxcomposite1
    override-prime: |
      snapcraftctl prime
      # force armhf
      sed -i 's/export SNAP_LAUNCHER/export ARCH="arm-linux-gnueabihf"\nexport SNAP_LAUNCHER/' bin/desktop-launch
  ffmpeg:
    source: https://github.com/RPi-Distro/ffmpeg.git
    source-depth: 1
    plugin: autotools
    after: [ pi-libs, desktop-qt5 ]
    build-environment:
      - LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAPCRAFT_STAGE/usr/lib"
    autotools-configure-parameters:
      - --prefix=/usr
      - --toolchain=hardened
      - --enable-gpl
      - --enable-stripping
      - --enable-avresample
      - --disable-filter=resample
      - --enable-avisynth
      - --enable-gnutls
      - --enable-ladspa
      - --enable-libaom
      - --enable-libass
      - --enable-libbluray
      - --enable-libbs2b
      - --enable-libcaca
      - --enable-libcdio
      - --enable-libcodec2
      - --enable-libflite
      - --enable-libfontconfig
      - --enable-libfreetype
      - --enable-libfribidi
      - --enable-libgme
      - --enable-libgsm
      - --enable-libjack
      - --enable-libmp3lame
      - --enable-libmysofa
      - --enable-libopenjpeg
      - --enable-libopenmpt
      - --enable-libopus
      - --enable-libpulse
      - --enable-librsvg
      - --enable-librubberband
      - --enable-libshine
      - --enable-libsnappy
      - --enable-libsoxr
      - --enable-libspeex
      - --enable-libssh
      - --enable-libtheora
      - --enable-libtwolame
      - --enable-libvidstab
      - --enable-libvorbis
      - --enable-libvpx
      - --enable-libwavpack
      - --enable-libwebp
      - --enable-libx265
      - --enable-libxml2
      - --enable-libxvid
      - --enable-libzmq
      - --enable-libzvbi
      - --enable-lv2
      - --enable-omx
      - --enable-openal
      - --enable-opengl
      - --enable-sdl2
      - --enable-omx-rpi
      - --enable-mmal
      - --enable-neon
      - --enable-rpi
      - --enable-version3
      - --disable-doc
      - --disable-programs
      - --enable-liblensfun
      - --enable-libopencore_amrnb
      - --enable-libopencore_amrwb
      - --enable-libtesseract
      - --enable-libvo_amrwbenc
      - --enable-libdc1394
      - --enable-libdrm
      - --enable-libiec61883
      - --enable-shared
      - --enable-libx264
      - --enable-libfdk-aac
      - --enable-nonfree
    override-build: |
      git apply -v $SNAPCRAFT_PROJECT_DIR/patches/ffmpeg.patch
      snapcraftctl build
    build-packages:
      - cleancss
      - doxygen
      - flite1-dev
      - frei0r-plugins-dev
      - ladspa-sdk
      - libaom-dev
      - libasound2-dev
      - libass-dev
      - libbluray-dev
      - libbs2b-dev
      - libbz2-dev
      - libcaca-dev
      - libcdio-paranoia-dev
      - libcodec2-dev
      - libdc1394-22-dev
      - libdrm-dev
      - libfdk-aac-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libfribidi-dev
      - libgl1-mesa-dev
      - libglx-dev
      - libgme-dev
      - libgnutls28-dev
      - libgsm1-dev
      - libiec61883-dev
      - libjack-dev
      - libavc1394-dev
      - liblensfun-dev
      - liblilv-dev
      - liblzma-dev
      - libmp3lame-dev
      - libmysofa-dev
      - libopenal-dev
      - libomxil-bellagio-dev
      - libopencore-amrnb-dev
      - libopencore-amrwb-dev
      - libopenjp2-7-dev
      - libopenmpt-dev
      - libopus-dev
      - libpulse-dev
      - librubberband-dev
      - librsvg2-dev
      - libsctp-dev
      - libsdl2-dev
      - libshine-dev
      - libsnappy-dev
      - libsoxr-dev
      - libspeex-dev
      - libssh-gcrypt-dev
      - libtesseract-dev
      - libtheora-dev
      - libtwolame-dev
      - libva-dev
      - libvdpau-dev
      - libvidstab-dev
      - libvo-amrwbenc-dev
      - libvorbis-dev
      - libvpx-dev
      - libwavpack-dev
      - libwebp-dev
      - libx264-dev
      - libx265-dev
      - libxcb-shape0-dev
      - libxcb-shm0-dev
      - libxcb-xfixes0-dev
      - libxml2-dev
      - libxv-dev
      - libxvidcore-dev
      - libxvmc-dev
      - libzmq3-dev
      - libzvbi-dev
      - pkg-config
      - texinfo
      - nasm
      - zlib1g-dev
    stage-packages:
      - freeglut3
      - libslang2
      - libusb-1.0-0
      - libaom0
      - libarchive13
      - libasound2
      - libasound2-plugins
      - libass9
      - libavc1394-0
      - libbluray2
      - libbs2b0
      - libcaca0
      - libcdio-cdda2
      - libcdio-paranoia2
      - libcdio18
      - libcodec2-0.9
      - libdc1394-22
      - libfdk-aac1
      - libfftw3-double3
      - libflite1
      - libgif7
      - libgl1
      - libglu1-mesa
      - libglx0
      - libgme0
      - libgomp1
      - libgsm1
      - libiec61883-0
      - liblensfun1
      - liblept5
      - liblilv-0-0
      - libmp3lame0
      - libmpg123-0
      - libmysofa1
      - libnorm1
      - libopenal1
      - libopencore-amrnb0
      - libopencore-amrwb0
      - libopenjp2-7
      - libopenmpt0
      - libopus0
      - libpgm-5.2-0
      - libpulse0
      - libraw1394-11
      - librubberband2
      - libsdl2-2.0-0
      - libserd-0-0
      - libshine3
      - libsnappy1v5
      - libsndio7.0
      - libsodium23
      - libsord-0-0
      - libsoxr0
      - libspeex-dbg
      - libsratom-0-0
      - libssh-gcrypt-4
      - libtesseract4
      - libtheora0
      - libtwolame0
      - libva-drm2
      - libva-x11-2
      - libva2
      - libvdpau1
      - libvidstab1.1
      - libvo-amrwbenc0
      - libvorbisfile3
      - libvpx6
      - libwavpack1
      - libwayland-cursor0
      - libwayland-egl1
      - libwebpmux3
      - libx264-155
      - libx265-179
      - libxss1
      - libxv1
      - libxvidcore4
      - libxxf86vm1
      - libzmq5
      - libzvbi0
    prime:
      - -usr/include
      - -usr/share
  vlc:
    plugin: autotools
    source: https://github.com/RPi-Distro/vlc.git
    source-branch: buster-rpt
    after: [ ffmpeg ]
    build-environment:
      - LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAPCRAFT_STAGE/usr/lib"
    autotools-configure-parameters:
      - --prefix=/usr
      - --config-cache
      - --disable-update-check
      - --enable-fast-install
      - --enable-a52
      - --enable-aa
      - --enable-aribsub
      - --enable-avahi
      - --enable-bluray
      - --enable-caca
      - --enable-chromecast
      - --enable-dbus
      - --enable-dca
      - --enable-dvbpsi
      - --enable-dvdnav
      - --enable-faad
      - --enable-flac
      - --enable-fluidsynth
      - --enable-freetype
      - --enable-fribidi
      - --enable-gles2
      - --enable-gnutls
      - --enable-harfbuzz
      - --enable-jack
      - --enable-kate
      - --enable-libass
      - --enable-libmpeg2
      - --enable-libxml2
      - --enable-lirc
      - --enable-live555
      - --enable-mad
      - --enable-matroska
      - --enable-mod
      - --enable-mpc
      - --enable-mpg123
      - --enable-mtp
      - --enable-ncurses
      - --enable-notify
      - --enable-ogg
      - --enable-opus
      - --enable-pulse
      - --enable-qt
      - --enable-realrtsp
      - --enable-samplerate
      - --enable-sdl-image
      - --enable-sftp
      - --enable-shine
      - --enable-shout
      - --enable-skins2
      - --enable-sndio
      - --enable-soxr
      - --enable-spatialaudio
      - --enable-speex
      - --enable-svg
      - --enable-svgdec
      - --enable-taglib
      - --enable-theora
      - --enable-twolame
      - --enable-upnp
      - --enable-vnc
      - --enable-vorbis
      - --enable-x264
      - --enable-x265
      - --enable-zvbi
      - --disable-d3d11va
      - --disable-decklink
      - --disable-directx
      - --disable-dsm
      - --disable-dxva2
      - --enable-fdkaac
      - --disable-fluidlite
      - --disable-freerdp
      - --disable-goom
      - --disable-gst-decode
      - --disable-libtar
      - --disable-macosx
      - --disable-macosx-avfoundation
      - --disable-macosx-qtkit
      - --disable-microdns
      - --disable-mfx
      - --disable-opencv
      - --disable-projectm
      - --disable-schroedinger
      - --disable-sparkle
      - --disable-srt
      - --disable-telx
      - --disable-vpx
      - --disable-vsxu
      - --disable-wasapi
      - --enable-alsa
      - --enable-dc1394
      - --enable-dv1394
      - --enable-libplacebo
      - --enable-linsys
      - --enable-nfs
      - --enable-omxil
      - --enable-udev
      - --enable-v4l2
      - --enable-wayland
      - --enable-vcd
      - --enable-smbclient
      - --disable-oss
      - --disable-crystalhd
      - --disable-mmx
      - --disable-sse
      - --enable-neon
      - --enable-mmal
      - --enable-mmal-avcodec
      - --disable-vdpau
      - --enable-libva
      - --disable-dav1d
      - --enable-aom
      - --disable-altivec
      - --disable-chromaprint
    override-build: |
      git apply -v $SNAPCRAFT_PROJECT_DIR/patches/mmal.patch
      snapcraftctl build
      sed -i 's;^Icon=vlc;Icon=/usr/share/icons/hicolor/256x256/apps/vlc.png;' \
          $SNAPCRAFT_PART_INSTALL/usr/share/applications/vlc.desktop
      # set version
      VER="$(grep AC_INIT ./configure.ac | sed 's/^.*, //;s/)//')"
      snapcraftctl set-version "$VER"
    build-packages:
      - autopoint
      - bison
      - gettext
      - flex
      - liba52-0.7.4-dev
      - libaa1-dev
      - libaribb24-dev
      - libavahi-client-dev
      - libcddb2-dev
      - libdca-dev
      - libdvbpsi-dev
      - libdvdnav-dev
      - libdvdread-dev
      - libebml-dev
      - libfaad-dev
      - libflac-dev
      - libfluidsynth-dev
      - libgtk-3-dev
      - libkate-dev
      - liblirc-dev
      - liblivemedia-dev
      - liblua5.2-dev
      - libmad0-dev
      - libmatroska-dev
      - libmpcdec-dev
      - libmpeg2-4-dev
      - libmsgpack-dev
      - libmtp-dev
      - libncursesw5-dev
      - libnfs-dev
      - libnotify-dev
      - libmodplug-dev
      - libplacebo-dev
      - libprotobuf-dev
      - libpulse-dev
      - libqt5svg5-dev
      - libqt5x11extras5-dev
      - libresid-builder-dev
      - librsvg2-dev
      - libsamplerate0-dev
      - libsdl-image1.2-dev
      - libsdl1.2-dev
      - libsecret-1-dev
      - libshout3-dev
      - libsidplay2-dev
      - libsmbclient-dev
      - libspatialaudio-dev
      - libspeex-dev
      - libspeexdsp-dev
      - libssh2-1-dev
      - libsystemd-dev
      - libtag1-dev
      - libudev-dev
      - libupnp-dev
      - libvncserver-dev
      - libx11-dev
      - libxcb-composite0-dev
      - libxcb-keysyms1-dev
      - libxcb-randr0-dev
      - libxcb-shm0-dev
      - libxcb-xv0-dev
      - libxcb1-dev
      - libxext-dev
      - libxi-dev
      - libxinerama-dev
      - libxml2-dev
      - libxpm-dev
      - libzvbi-dev
      - lua5.2
      - pkg-config
      - protobuf-compiler
      - python3
      - qtbase5-dev
      - qtbase5-private-dev
      - wayland-protocols
      - zlib1g-dev
      - libdrm-dev
      - libxrandr-dev
    stage-packages:
      - liba52-0.7.4
      - libaa1
      - libaribb24-0
      - libasn1-8-heimdal
      - libatk-bridge2.0-0
      - libatspi2.0-0
      - libbasicusageenvironment1
      - libcddb2
      - libdca0
      - libdvbpsi10
      - libdvdnav4
      - libdvdread7
      - libebml4v5
      - libepoxy0
      - libfaad2
      - libfluidsynth2
      - libgpm2
      - libgroupsock8
      - libgssapi3-heimdal
      - libgtk-3-0
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libinstpatch-1.0-2
      - libixml10
      - libjansson4
      - libkate1
      - libkrb5-26-heimdal
      - liblcms2-2
      - libldap-2.4-2
      - libldb2
      - liblirc-client0
      - liblivemedia77
      - liblua5.2-0
      - libmad0
      - libmatroska6v5
      - libmodplug1
      - libmpcdec6
      - libmpeg2-4
      - libmtp9
      - libnfs13
      - libnotify4
      - libplacebo7
      - libprotobuf-lite17
      - libqt5x11extras5
      - libresid-builder0c2a
      - libroken18-heimdal
      - libsasl2-2
      - libsdl-image1.2
      - libsdl1.2debian
      - libsecret-1-0
      - libshout3
      - libsidplay2
      - libsmbclient
      - libspatialaudio0
      - libssh2-1
      - libtag1v5-vanilla
      - libtalloc2
      - libtdb1
      - libtevent0
      - libupnp13
      - libusageenvironment3
      - libva-wayland2
      - libvncclient1
      - libvulkan1
      - libwbclient-sssd
      - libwbclient0
      - libwind0-heimdal
      - libxcb-composite0
      - libxcb-xv0
      - libxpm4
      - samba-libs
    prime:
      - -usr/i686-linux-gnu
      - -usr/include
    stage:
      - -usr/lib/arm-linux-gnueabihf/libasound.so.2
      - -usr/lib/arm-linux-gnueabihf/libjack.so.0
      - -usr/lib/arm-linux-gnueabihf/libjackserver.so.0
  locales-launch:
    plugin: nil
    stage-snaps:
      - locales-launch
    stage-packages:
      - libc-bin
      - locales
  init-checks:
    plugin: dump
    source: scripts
    stage-packages:
      - yad
    organize:
      checks.sh: bin/checks
  cleanup:
    plugin: nil
    after: [ vlc ]
    override-prime: |
      # do not ship static libs or any libtool remainings
      find . -name '*.la*' -delete
      find . -name '*.a' -delete
      # delete any remaining headers
      find . -name '*.h' -delete
      # link mesa libs to correct search names
      cd ${SNAPCRAFT_PRIME}/usr/lib/arm-linux-gnueabihf/
      ln -sf libEGL.so.1 libEGL.so || true
      ln -sf libGLESv2.so.2 libGLESv2.so || true
      # clean up doc dirs
      find ${SNAPCRAFT_PRIME}/usr/share/doc/ -type f -not -name 'copyright' -delete || true
      rm ${SNAPCRAFT_PRIME}/usr/share/doc/*/*.gz 2>/dev/null || true
      rm ${SNAPCRAFT_PRIME}/usr/share/doc/*/README* 2>/dev/null || true
      find ${SNAPCRAFT_PRIME}/usr/share -type d -empty -delete || true
      # remove pre-generated locales, we generate them on first start
      rm -rf ${SNAPCRAFT_PRIME}/usr/lib/locale/* 2>/dev/null || true
      # drop useless dri drivers
      find ${SNAPCRAFT_PRIME}/usr/lib/arm-linux-gnueabihf/dri/ -type f -not -name 'vc4_dri.so' \
          -not -name 'v3d_dri.so' -not -name 'swrast_dri.so' -delete || true
